# Generated by Django 5.0.6 on 2024-05-28 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel order', 'Can cancel order')]},
        ),
    ]
